### ISSUE TITLE
Sprint 2 Checklist: 3.6 and 3.7

### ISSUE THREAD

**Issue by blackstar3092** [blackstar3092/sprint_2#1]
3.6: Conditionals

- [ ] In a Jupyter notebook, include text explaining concepts of and definitions/syntax behind conditionals
- [ ] Create a conditionals script (3.6) that runs on a Jupyter Notebook
- [ ] Create a hack for class to solve on 3.6 terms and code taught (ex. write a code snippet with a conditional that follows certain action/output requirements)
- [ ] Complete and include multiple popcorn hacks (at least 3)

3.7 Nested Conditionals

- [ ] Create a nested conditionals script that builds upon the concepts taught in 3.6
- [ ] Create a hack for class to solve on 3.7 terms and code taught (ex. write a code snippet with nested conditionals that solve a problem, such as multiple decisions being made)
- [ ] Complete and include multiple popcorn hacks (at least 3)
